name: Release Scala Client to Maven

on:
  # TODO: pull_request has to be removed before mergin
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: run-python-tests
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '23.3'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Scala and SBT
        env:
          SBT_VERSION: 1.10.7
          SCALA_VERSION: 2.13.15
        run: |
          curl -s -O https://downloads.lightbend.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.deb
          sudo apt install -y ./scala-${SCALA_VERSION}.deb
          curl -s -L -O https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz
          tar -xzvf ./sbt-${SBT_VERSION}.tgz
          echo "$PWD/sbt/bin" >> "${GITHUB_PATH}"
      - name: Build Armada Scala Client
        run: |
          go run github.com/magefile/mage@v1.14.0 -v buildScala
      # TODO: credentials for Sonatype missing
      - name: Publish package to Maven
        run: |
          cd client/scala/scala-armada-client
          sbt -Dsbt.io.implicit.relative.glob.conversion=allow publish

